// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwsSWjZuQKHhiutPtByBnWlDujuMtSzk',
    appId: '1:397855418130:web:97760811dba4fff5ad75cb',
    messagingSenderId: '397855418130',
    projectId: 'gasapp-fc19d',
    authDomain: 'gasapp-fc19d.firebaseapp.com',
    storageBucket: 'gasapp-fc19d.appspot.com',
    measurementId: 'G-S7MT0BJ140',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIUSSlRMQHNaQV9WclbfI0BuKLnh18hF8',
    appId: '1:397855418130:android:c3b0dcea30920c9aad75cb',
    messagingSenderId: '397855418130',
    projectId: 'gasapp-fc19d',
    storageBucket: 'gasapp-fc19d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwn5Ufo-BwgbFuQZeSl3hJ0cTdpvKDrTQ',
    appId: '1:397855418130:ios:83172ad8785dd3d3ad75cb',
    messagingSenderId: '397855418130',
    projectId: 'gasapp-fc19d',
    storageBucket: 'gasapp-fc19d.appspot.com',
    iosClientId: '397855418130-04ucji8f2hjo1c0cnan1v0a4ad0jecg8.apps.googleusercontent.com',
    iosBundleId: 'com.davide.gas.gas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwn5Ufo-BwgbFuQZeSl3hJ0cTdpvKDrTQ',
    appId: '1:397855418130:ios:749e76e6c46f9f05ad75cb',
    messagingSenderId: '397855418130',
    projectId: 'gasapp-fc19d',
    storageBucket: 'gasapp-fc19d.appspot.com',
    iosClientId: '397855418130-6sl1rfvj8j1p2rtdhcm0q805s82um32q.apps.googleusercontent.com',
    iosBundleId: 'com.davide.gas.gas.RunnerTests',
  );
}
